### ISSUE TITLE
importError

### ISSUE THREAD

**Issue by ZqCATCAT** [yoshitomo-matsubara/sc2-benchmark#112]
Hello, i have a problem to run the sc2-benchmark. There is no 'model_urls' in 'torchvision.models.segmentation.deeplabv3', but i exactly install torchvision0.11.1.
![image](https://user-images.githubusercontent.com/88480317/206894125-e1d7bf6b-0291-44f9-a055-e50c35fa8af8.png)
![image](https://user-images.githubusercontent.com/88480317/206894143-1d2d7d5c-4e82-4b56-ad7f-aa8215840ece.png)

**Comment by yoshitomo-matsubara** [comment]
Thank you @ZqCATCAT for reporting that.

I forgot to update the minimum requirements in setup.py for the change (`model_url` was introduced to deeplab.py from [v0.12.0](https://github.com/pytorch/vision/blob/v0.12.0/torchvision/models/segmentation/deeplabv3.py))

Please update torch and torchvision with 1.11.0>= and 0.12.0>= respectively. I will edit `setup.py` soon for next version release
