### ISSUE TITLE
[BUG] Compatibility issue, ckpt loading

### ISSUE THREAD

**Issue by lixinghe1999** [yoshitomo-matsubara/sc2-benchmark#141]
Please use [Discussions](https://github.com/yoshitomo-matsubara/sc2-benchmark/discussions) to ask questions.

**Describe the bug**
Running the example code on downloaded ckpt gets errors. The error applies to all the example code, and the error log is similar, seems like the shape of _quantized_cdf is always defined to be [24, 23]

**To Reproduce**
Provide
1. python script/task/object_detection.py  --config configs/coco2017/supervised_compression/end-to-end/faster_rcnn_splittable_resnet50-fp-beta1.28e-8_fpn.yaml   --log log/coco2017/supervised_compression/end-to-end/faster_rcnn_splittable_resnet50-fp-beta1.28e-8_fpn.txt -test_only
2. No
3. No modification
4. RuntimeError: Error(s) in loading state_dict for BaseRCNN:
        size mismatch for backbone.body.bottleneck_layer.entropy_bottleneck._quantized_cdf: copying a param with shape torch.Size([24, 31]) from checkpoint, the shape in current model is torch.Size([24, 23]).

**Expected behavior**
The example code should run smoothly.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Python ver. 3.8
 - sc2bench and torchdistill vers. v0.0.4 and 0.0.1

**Additional context**
I guess maybe it is the compatibility issue between compressai

**Comment by yoshitomo-matsubara** [comment]
Hi @lixinghe1999 ,

torchdistill 0.0.1 is too old and not supported.
Can you provide the version of compressai that you're using?
Also, use a better issue title for better search

**Comment by lixinghe1999** [comment]
> Hi @lixinghe1999 ,
> 
> torchdistill 0.0.1 is too old and not supported. Can you provide the version of compressai that you're using? Also, use a better issue title for better search

Updated version:
compressai         1.1.9
torchdistill       0.3.1
sc2bench           0.0.4

seems match the environment config but still get the same errors:
`
RuntimeError: Error(s) in loading state_dict for BaseRCNN:
        size mismatch for backbone.body.bottleneck_layer.entropy_bottleneck._quantized_cdf: copying a param with shape torch.Size([24, 31]) from checkpoint, the shape in current model is torch.Size([24, 23]).
`

Command:
```
python script/task/object_detection.py     --config configs/coco2017/supervised_compression/end-to-end/faster_rcnn_spli
ttable_resnet50-fp-beta1.28e-8_fpn.yaml    --log log/coco2017/supervised_compression/end-to-end/faster_rcnn_splittable_resnet50-fp-beta1.28e-8_fpn.txt -test_only
```

**Comment by yoshitomo-matsubara** [comment]
Hi @lixinghe1999 

Thanks for sharing more details.
The numbers you're seeing like 23 is not hardcoded in my repo, but more like randomly initialized or hardcoded in compressai package.
If you try other checkpoints (e.g. with different beta numbers), you may see different numbers and work without errors.

At that time I was running experiments (a few years ago), sometimes the trained model weights for compressai modules cannot be reloaded due to such issues. Some workarounds I tried at that time were using `.update()` of compressai modules before loading state dict or using different machines (and/or different versions or OS).


I also found a similar issue reported in the compressai repo, and this workaround may help you.
https://github.com/InterDigitalInc/CompressAI/issues/75

https://github.com/InterDigitalInc/CompressAI/blob/743680befc146a6d8ee7840285584f2ce00c3732/compressai/models/utils.py#L94

**Comment by lixinghe1999** [comment]
> Hi @lixinghe1999
> 
> Thanks for sharing more details. The numbers you're seeing like 23 is not hardcoded in my repo, but more like randomly initialized or hardcoded in compressai package. If you try other checkpoints (e.g. with different beta numbers), you may see different numbers and work without errors.
> 
> At that time I was running experiments (a few years ago), sometimes the trained model weights for compressai modules cannot be reloaded due to such issues. Some workarounds I tried at that time were using `.update()` of compressai modules before loading state dict or using different machines (and/or different versions or OS).
> 
> I also found a similar issue reported in the compressai repo, and this workaround may help you. [InterDigitalInc/CompressAI#75](https://github.com/InterDigitalInc/CompressAI/issues/75)
> 
> https://github.com/InterDigitalInc/CompressAI/blob/743680befc146a6d8ee7840285584f2ce00c3732/compressai/models/utils.py#L94

Thank you for getting back to me. I just found the reasons: even though I only test object detection, I **must** download the image classification model as well. I am still reading the code to see why, but I guess the object detection inherits the image classification. LOL.

**Comment by yoshitomo-matsubara** [comment]
Yes, many of the models use checkpoints for image classification model (used as backbone for object detection and semantic segmentation models), and it is very common to use pretrained image classification models as backbones for such tasks.

**Comment by yoshitomo-matsubara** [comment]
Closing this for now. Feel free to reopen if you still face the same issue.
